{% set name = "bson" %}
{% set version = "0.5.6" %}
{% set sha256 = "28a4db93d956474f0dac150324a3945eeb4e15e1d2707fecb90e5edd9fedd76e" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
    - pip
  run:
    - python
    - six
    - pytz

test:
  imports:
    - bson

about:
  summary: Independent BSON codec for Python that doesn't depend on MongoDB.
  home: https://github.com/py-bson/bson
  license: BSD-3-Clause
  license_family: BSD

extra:
  recipe-maintainers:
    - robmcmullen
    - ChrisBarker-NOAA
